app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as'   => 'home',
    'uses' => function () {
        return redirect()->route('categories.index');
    }
]);

Route::resource('categories', 'CategoriesController');
Route::resource('categories.threads', 'ThreadsController');
Route::resource('categories.threads.posts', 'PostsController');

Route::group([
    'prefix'     => 'admin',
    'middleware' => 'admin',
], function () {
    Route::get('index', [
        'as'   => 'admin.index',
        'uses' => 'AdminController@index',
    ]);

    Route::resource('categories', 'AdminCategoriesController', [
        'expect' => ['show',],
    ]);

    Route::resource('users', 'AdminUsersController');
});

// Authentication routes
Route::get('auth/login', [
    'as'   => 'auth.login',
    'uses' => 'AuthenticationController@getLogin',
]);
Route::post('auth/login', [
    'as'   => 'auth.login.post',
    'uses' => 'AuthenticationController@postLogin',
]);
Route::get('auth/logout', [
    'as'   => 'auth.logout',
    'uses' => 'AuthenticationController@getLogout',
]);

// Registration routes
Route::get('auth/register', [
    'as'   => 'auth.register',
    'uses' => 'AuthenticationController@getRegister',
]);
Route::post('auth/register', [
    'as'   => 'auth.register.post',
    'uses' => 'AuthenticationController@postRegister',
]);
Route::get('auth/register/confirm/{email?}/{token?}', [
    'as'   => 'auth.register.confirm',
    'uses' => 'AuthenticationController@getConfirm',
]);
Route::post('auth/register/confirm', [
    'as'   => 'auth.register.confirm.post',
    'uses' => 'AuthenticationController@postConfirm',
]);

// Password reset routes
Route::get('auth/password/email', [
    'as'   => 'auth.password',
    'uses' => 'AuthenticationController@getPassword',
]);
Route::post('auth/password/email', [
    'as'   => 'auth.password.post',
    'uses' => 'AuthenticationController@postPassword',
]);
Route::get('auth/password/reset/{email?}/{token?}', [
    'as'   => 'auth.password.reset',
    'uses' => 'AuthenticationController@getReset',
]);
Route::post('auth/password/reset', [
    'as'   => 'auth.password.reset.post',
    'uses' => 'AuthenticationController@postReset',
]);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{

    use SoftDeletes;

    protected $table = 'posts';

    protected $fillable = [
        'title',
        'body',
    ];

    protected $dates = [
        'deleted_at',
    ];

    public function thread()
    {
        return $this->belongsTo('App\Thread');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\PostRequest;
use App\Post;
use App\Thread;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;

class PostsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['expect' => ['index']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @param $categoryId
     * @param $threadId
     * @return Response
     */
    public function index($categoryId, $threadId)
    {
        $thread = Thread::with([
            'category' => function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            },
            'posts'    => function ($query) {
                $query->orderBy('created_at', 'asc');
            }
        ])
            ->findOrFail($threadId);

        return view('posts.index', compact('thread'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param $categoryId
     * @param $threadId
     * @return Response
     */
    public function create($categoryId, $threadId)
    {
        if (!Sentinel::getUser()->hasAccess(['posts.create'])) {
            abort(401);
        }

        $thread = Thread::with([
            'category' => function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            }
        ])
            ->findOrFail($threadId);

        $post = new Post();
        $post->title = 'Re: ' . $thread->posts->first()->title;

        return view('posts.create', compact('thread', 'post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param $categoryId
     * @param $threadId
     * @param PostRequest $request
     * @return Response
     */
    public function store($categoryId, $threadId, PostRequest $request)
    {
        if (!Sentinel::getUser()->hasAccess(['posts.create'])) {
            abort(401);
        }

        $thread = Thread::with([
            'category' => function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            }
        ])
            ->findOrFail($threadId);

        $post = new Post($request->all());
        $post->user_id = Sentinel::getUser()->id;
        $post->thread_id = $thread->id;
        $post->save();

        return redirect()->route('categories.threads.posts.index', [$thread->category->id, $thread->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param $categoryId
     * @param $threadId
     * @param $postId
     * @return Response
     */
    public function show($categoryId, $threadId, $postId)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $categoryId
     * @param $threadId
     * @param $postId
     * @return Response
     */
    public function edit($categoryId, $threadId, $postId)
    {
        $post = Post::with([
            'thread'          => function ($query) use ($threadId) {
                $query->where('id', $threadId);
            },
            'thread.category' => function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            },
        ])
            ->findOrFail($postId);

        if (
            (Sentinel::getUser()->id == $post->user->id && !Sentinel::getUser()->hasAccess(['posts.own.edit']))
            || (Sentinel::getUser()->id != $post->user->id && !Sentinel::getUser()->hasAccess(['posts.others.edit']))
        ) {
            abort(401);
        }

        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param $categoryId
     * @param $threadId
     * @param $postId
     * @param PostRequest $request
     * @return Response
     */
    public function update($categoryId, $threadId, $postId, PostRequest $request)
    {
        $post = Post::with([
            'thread'          => function ($query) use ($threadId) {
                $query->where('id', $threadId);
            },
            'thread.category' => function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            },
        ])
            ->findOrFail($postId);

        if (
            (Sentinel::getUser()->id == $post->user->id && !Sentinel::getUser()->hasAccess(['posts.own.edit']))
            || (Sentinel::getUser()->id != $post->user->id && !Sentinel::getUser()->hasAccess(['posts.others.edit']))
        ) {
            abort(401);
        }

        $post->update($request->all());

        return redirect()->route('categories.threads.posts.index', [$post->thread->category->id, $post->thread->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $categoryId
     * @param $threadId
     * @param $postId
     * @return Response
     */
    public function destroy($categoryId, $threadId, $postId)
    {
        $post = Post::with([
            'thread'          => function ($query) use ($threadId) {
                $query->where('id', $threadId);
            },
            'thread.category' => function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            },
        ])
            ->findOrFail($postId);

        // don't allow deleting threads here
        if ($post->id == $post->thread->posts->first()->id) {
            abort(401);
        }

        if (
            // own post and no rights to destroy it
            (Sentinel::getUser()->id == $post->user->id && !Sentinel::getUser()->hasAccess(['posts.own.destroy']))

            // others post and no rights to destroy it
            || (Sentinel::getUser()->id != $post->user->id && !Sentinel::getUser()->hasAccess(['posts.others.destroy']))
        ) {
            abort(401);
        }

        $post->delete();

        return redirect()->route('categories.threads.posts.index', [$post->thread->category->id, $post->thread->id]);
    }
}

resources/views/posts/_form.blade.php
<!-- Title form input -->
<div class="form-group">
    {!! Form::label('title', 'Title', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::text('title', null, ['placeholder' => 'Title', 'class' => 'form-control']) !!}
    </div>
</div>

<!-- Body form input -->
<div class="form-group">
    {!! Form::label('body', 'Body', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('body', null, ['placeholder' => 'Body', 'class' => 'form-control']) !!}
        <span class="help-block">
            <b>What is this?</b>
            Forum messages are parsed using <a href="http://spec.commonmark.org/0.19/">CommonMark</a>.
            Quick reference can be found <a href="http://en.wikipedia.org/wiki/Markdown#Example">on Wikipedia</a>.
        </span>
    </div>
</div>

<!-- Submit submit button -->
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        {!! Form::submit('Submit', ['class' => 'btn btn-primary form-control']) !!}
    </div>
</div>

resources/views/posts/create.blade.php
@extends('app')

@section('title')
    Reply - {{ $thread->posts->first()->title }} - {{ $thread->category->name }} -
@stop

@section('content')
    <div class="container">
        <ol class="breadcrumb where-am-i">
            <li><a href="{{ route('categories.index') }}">Forums</a></li>
            <li><a href="{{ route('categories.threads.index', [$thread->category->id]) }}">{{ $thread->category->name }}</a></li>
            <li><a href="{{ route('categories.threads.posts.index', [$thread->category->id, $thread->id]) }}">{{ $thread->posts->first()->title }}</a></li>
            <li class="active">New reply</li>
        </ol>

        <div class="page-header page-heading">
            <h1>
                New reply
            </h1>
        </div>

        @include('errors._form')
        {!! Form::model($post, ['route' => ['categories.threads.posts.store', $thread->category->id, $thread->id], 'class' => 'form-horizontal']) !!}
        @include('posts._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/posts/edit.blade.php
@extends('app')

@section('title')
    Edit {{ $post->title }} - {{ $post->thread->posts->first()->title }} - {{ $post->thread->category->name }} -
@stop

@section('content')
    <div class="container">
        <ol class="breadcrumb where-am-i">
            <li><a href="{{ route('categories.index') }}">Forums</a></li>
            <li><a href="{{ route('categories.threads.index', [$post->thread->category->id]) }}">{{ $post->thread->category->name }}</a></li>
            <li><a href="{{ route('categories.threads.posts.index', [$post->thread->category->id, $post->thread->id]) }}">{{ $post->thread->posts->first()->title }}</a></li>
            <li class="active">Edit post</li>
        </ol>

        <div class="page-header page-heading">
            <h1>
                Editing post <i>"{{ $post->title }}"</i>
            </h1>
        </div>

        @include('errors._form')

        {!! Form::model($post, ['route' => ['categories.threads.posts.update', $post->thread->category->id, $post->thread->id, $post->id], 'method' => 'patch', 'class' => 'form-horizontal']) !!}
        @include('posts._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/posts/index.blade.php
@extends('app')

@section('title')
    {{ $thread->posts->first()->title }} - {{ $thread->category->name }} -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('categories.index') }}">Forums</a></li>
            <li><a href="{{ route('categories.threads.index', [$thread->category->id]) }}">{{ $thread->category->name }}</a></li>
            <li class="active">{{ $thread->posts->first()->title }}</li>
        </ol>

        <div class="page-header page-heading">
            <h1>{{ $thread->posts->first()->title }}</h1>
        </div>

        <p class="text-right">
            @if(Sentinel::check())
                @if(Sentinel::getUser()->hasAccess(['posts.create']))
                    <a class="btn btn-primary btn-lg" href="{{ route('categories.threads.posts.create', [$thread->category->id, $thread->id]) }}">New Reply</a>
                @else
                    You do not have permission to reply threads
                @endif
            @else
                <a href="{{ url('/auth/login') }}">Login</a> or <a href="{{ url('/auth/register') }}">Register</a> to reply thread
            @endif
        </p>

        <article class="forum-thread">
            @foreach($thread->posts as $i => $post)
                <section class="row row-eq-height">
                    <div class="col-md-3 user-info">
                        <img class="img-thumbnail" src="http://placehold.it/100" alt="{{ $post->user->first_name }}" /><br />
                        <a href="#">{{ $post->user->first_name }}</a><br />
                        {{ $post->user->roles->first()->name }}
                    </div>
                    <div class="col-md-9">
                        <h4 class="pull-left">
                            {{ $post->title }}<br />
                            <small class="text-muted">
                                <abbr title="{{ $post->created_at->format('d.m.Y H:i:s') }}">
                                    <time datetime="{{ $post->created_at->format('d.m.Y H:i:s') }}">{{ $post->created_at->diffForHumans() }}</time>
                                </abbr>
                            </small>
                        </h4>
                        <div class="pull-right" style="padding-top: 10px;">
                            @if(
                                Sentinel::check()
                                && (
                                    Sentinel::getUser()->id == $post->user->id
                                    && Sentinel::getUser()->hasAccess(['posts.own.edit'])
                                )
                                || (
                                    Sentinel::getUser()->id != $post->user->id
                                    && Sentinel::getUser()->hasAccess(['posts.others.edit'])
                                ))
                                <a href="{{ route('categories.threads.posts.edit', [$thread->category->id, $thread->id, $post->id]) }}" class="btn btn-primary btn-xs">Edit</a>
                            @endif

                            @if(
                                Sentinel::check()
                                && $i == 0
                                && (
                                    (
                                        Sentinel::getUser()->id == $post->user->id
                                        && Sentinel::getUser()->hasAccess(['threads.own.destroy'])
                                    )
                                    || (
                                        Sentinel::getUser()->id != $post->user->id
                                        && Sentinel::getUser()->hasAccess(['threads.others.destroy'])
                                    )
                                ))
                                {!! Form::open(['route' => ['categories.threads.destroy', $thread->category->id, $thread->id], 'method' => 'delete', 'style' => 'display:inline']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                                {!! Form::close() !!}
                            @elseif(
                                Sentinel::check()
                                && $i != 0
                                && (
                                    (
                                        Sentinel::getUser()->id == $post->user->id
                                        && Sentinel::getUser()->hasAccess(['posts.own.destroy'])
                                    )
                                    || (
                                        Sentinel::getUser()->id != $post->user->id
                                        && Sentinel::getUser()->hasAccess(['posts.others.destroy'])
                                    )
                                ))
                                {!! Form::open(['route' => ['categories.threads.posts.destroy', $thread->category->id, $thread->id, $post->id], 'method' => 'delete', 'style' => 'display:inline']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                                {!! Form::close() !!}
                            @endif
                        </div>
                        <div class="clearfix"></div>
                        {!! $post->body !!}
                    </div>
                </section>
            @endforeach
        </article>
    </div>
@stop