app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as'   => 'home',
    'uses' => function () {
        return redirect()->route('categories.index');
    }
]);

Route::resource('categories', 'CategoriesController');
Route::resource('categories.threads', 'ThreadsController');
Route::resource('categories.threads.posts', 'PostsController');

Route::group([
    'prefix'     => 'admin',
    'middleware' => 'admin',
], function () {
    Route::get('index', [
        'as'   => 'admin.index',
        'uses' => 'AdminController@index',
    ]);

    Route::resource('categories', 'AdminCategoriesController', [
        'expect' => ['show',],
    ]);

    Route::resource('users', 'AdminUsersController');
});

// Authentication routes
Route::get('auth/login', [
    'as'   => 'auth.login',
    'uses' => 'AuthenticationController@getLogin',
]);
Route::post('auth/login', [
    'as'   => 'auth.login.post',
    'uses' => 'AuthenticationController@postLogin',
]);
Route::get('auth/logout', [
    'as'   => 'auth.logout',
    'uses' => 'AuthenticationController@getLogout',
]);

// Registration routes
Route::get('auth/register', [
    'as'   => 'auth.register',
    'uses' => 'AuthenticationController@getRegister',
]);
Route::post('auth/register', [
    'as'   => 'auth.register.post',
    'uses' => 'AuthenticationController@postRegister',
]);
Route::get('auth/register/confirm/{email?}/{token?}', [
    'as'   => 'auth.register.confirm',
    'uses' => 'AuthenticationController@getConfirm',
]);
Route::post('auth/register/confirm', [
    'as'   => 'auth.register.confirm.post',
    'uses' => 'AuthenticationController@postConfirm',
]);

// Password reset routes
Route::get('auth/password/email', [
    'as'   => 'auth.password',
    'uses' => 'AuthenticationController@getPassword',
]);
Route::post('auth/password/email', [
    'as'   => 'auth.password.post',
    'uses' => 'AuthenticationController@postPassword',
]);
Route::get('auth/password/reset/{email?}/{token?}', [
    'as'   => 'auth.password.reset',
    'uses' => 'AuthenticationController@getReset',
]);
Route::post('auth/password/reset', [
    'as'   => 'auth.password.reset.post',
    'uses' => 'AuthenticationController@postReset',
]);

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Thread extends Model
{

    use SoftDeletes;

    protected $table = 'threads';

    protected $fillable = [
        'is_locked',
        'is_sticky',
    ];

    protected $dates = [
        'deleted_at',
    ];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function posts()
    {
        return $this->hasMany('App\Post');
    }

}

app/Http/Controllers/ThreadsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests;
use App\Http\Requests\PostRequest;
use App\Post;
use App\Thread;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;

class ThreadsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['expect' => ['index']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @param $categoryId
     * @return Response
     */
    public function index($categoryId)
    {
        $category = Category::with([
            'threads' => function ($query) {
                $query->orderBy('updated_at', 'desc');
            },
            'threads.posts' => function ($query) {
                $query->orderBy('created_at', 'asc');
            },
            'threads.posts.user',
        ])
            ->findOrFail($categoryId);

        return view('threads.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param $categoryId
     * @return Response
     */
    public function create($categoryId)
    {
        if (!Sentinel::getUser()->hasAccess(['threads.create'])) {
            abort(401);
        }

        $category = Category::findOrFail($categoryId);

        return view('threads.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param $categoryId
     * @param PostRequest $request
     * @return Response
     */
    public function store($categoryId, PostRequest $request)
    {
        if (!Sentinel::getUser()->hasAccess(['threads.create'])) {
            abort(401);
        }

        $category = Category::findOrFail($categoryId);

        $thread = new Thread();
        $thread->category_id = $category->id;
        $thread->save();

        $post = new Post($request->all());
        $post->user_id = Sentinel::getUser()->id;
        $post->thread_id = $thread->id;
        $post->save();

        return redirect()->route('categories.threads.posts.index', [$category->id, $thread->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param $categoryId
     * @param $threadId
     * @return Response
     */
    public function show($categoryId, $threadId)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $categoryId
     * @param $threadId
     * @return Response
     */
    public function edit($categoryId, $threadId)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param $categoryId
     * @param $threadId
     * @return Response
     */
    public function update($categoryId, $threadId)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $categoryId
     * @param $threadId
     * @return Response
     */
    public function destroy($categoryId, $threadId)
    {
        $thread = Thread::with([
            'category' => function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            },
            'posts'    => function ($query) {
                $query->orderBy('created_at', 'asc');
            }
        ])
            ->findOrFail($threadId);

        if (
            // own thread and no rights to destroy it
            (Sentinel::getUser()->id == $thread->posts->first()->user->id && !Sentinel::getUser()->hasAccess(['threads.own.destroy']))

            // others thread and no rights to destroy it
            || (Sentinel::getUser()->id != $thread->posts->first()->user->id && !Sentinel::getUser()->hasAccess(['threads.others.destroy']))
        ) {
            abort(401);
        }

        $thread->posts()->delete();
        $thread->delete();

        return redirect()->route('categories.threads.index', [$thread->category->id]);
    }
}

resources/views/threads/create.blade.php
@extends('app')

@section('title')
    New thread - {{ $category->name }} -
@stop

@section('content')
    <div class="container">
        <ol class="breadcrumb where-am-i">
            <li><a href="{{ route('categories.index') }}">Forums</a></li>
            <li><a href="{{ route('categories.threads.index', [$category->id]) }}">{{ $category->name }}</a></li>
            <li class="active">New thread</li>
        </ol>

        <div class="page-header page-heading">
            <h1>
                New thread
            </h1>
        </div>

        @include('errors._form')

        {!! Form::model($post = new \App\Post, ['route' => ['categories.threads.store', $category->id], 'class' => 'form-horizontal']) !!}
        @include('posts._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/threads/index.blade.php
@extends('app')

@section('title')
    {{ $category->name }} -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('categories.index') }}">Forums</a></li>
            <li class="active">{{ $category->name }}</li>
        </ol>

        <div class="page-header page-heading">
            <h1>{{ $category->name }}</h1>
        </div>

        <p class="text-right">
            @if(Sentinel::check())
                @if(Sentinel::getUser()->hasAccess(['threads.create']))
                    <a class="btn btn-primary btn-lg" href="{{ route('categories.threads.create', [$category->id]) }}">New Thread</a>
                @else
                    You do not have permission to create new threads
                @endif
            @else
                <a href="{{ url('/auth/login') }}">Login</a> or <a href="{{ url('/auth/register') }}">Register</a> to create thread
            @endif
        </p>

        <table class="table forum">
            <thead>
            <tr>
                <th colspan="4">{{ $category->name }}</th>
            </tr>
            </thead>
            <tbody>
            @foreach($category->threads as $thread)
                <tr>
                    <td class="icon text-center">
                        <i class="fa fa-heart fa-2x text-danger"></i>
                    </td>
                    <td>
                        <a href="{{ route('categories.threads.posts.index', [$category->id, $thread->id]) }}">{{ $thread->posts->first()->title }}</a><br />
                        <small class="text-muted">
                            by <a href="#">{{ $thread->posts->first()->user->first_name }}</a>
                            <abbr title="{{ $thread->posts->first()->created_at->format('d.m.Y H:i:s') }}">
                                <time datetime="{{ $thread->posts->first()->created_at->format('d.m.Y H:i:s') }}">
                                    {{ $thread->posts->first()->created_at->diffForHumans() }}
                                </time>
                            </abbr>
                        </small>
                    </td>
                    <td class="text-center hidden-xs hidden-sm">
                        {{ $thread->posts->count() - 1 }}<br />
                        <small class="text-muted">Replies</small>
                    </td>
                    <td class="hidden-xs hidden-sm text-right">
                        @if($thread->posts->count() <= 1)
                            <span class="text-muted">
                                No replies
                            </span>
                        @else
                            Last post by <a href="#">{{ $thread->posts->last()->user->first_name }}</a><br />
                            <small class="text-muted">
                                <abbr title="{{ $thread->posts->last()->created_at->format('d.m.Y H:i:s') }}">
                                    <time datetime="{{ $thread->posts->last()->created_at->format('d.m.Y H:i:s') }}">
                                        {{ $thread->posts->last()->created_at->diffForHumans() }}
                                    </time>
                                </abbr>
                            </small>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop