app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as'   => 'home',
    'uses' => function () {
        return redirect()->route('categories.index');
    }
]);

Route::resource('categories', 'CategoriesController');
Route::resource('categories.threads', 'ThreadsController');
Route::resource('categories.threads.posts', 'PostsController');

Route::group([
    'prefix'     => 'admin',
    'middleware' => 'admin',
], function () {
    Route::get('index', [
        'as'   => 'admin.index',
        'uses' => 'AdminController@index',
    ]);

    Route::resource('categories', 'AdminCategoriesController', [
        'expect' => ['show',],
    ]);

    Route::resource('users', 'AdminUsersController');
});

// Authentication routes
Route::get('auth/login', [
    'as'   => 'auth.login',
    'uses' => 'AuthenticationController@getLogin',
]);
Route::post('auth/login', [
    'as'   => 'auth.login.post',
    'uses' => 'AuthenticationController@postLogin',
]);
Route::get('auth/logout', [
    'as'   => 'auth.logout',
    'uses' => 'AuthenticationController@getLogout',
]);

// Registration routes
Route::get('auth/register', [
    'as'   => 'auth.register',
    'uses' => 'AuthenticationController@getRegister',
]);
Route::post('auth/register', [
    'as'   => 'auth.register.post',
    'uses' => 'AuthenticationController@postRegister',
]);
Route::get('auth/register/confirm/{email?}/{token?}', [
    'as'   => 'auth.register.confirm',
    'uses' => 'AuthenticationController@getConfirm',
]);
Route::post('auth/register/confirm', [
    'as'   => 'auth.register.confirm.post',
    'uses' => 'AuthenticationController@postConfirm',
]);

// Password reset routes
Route::get('auth/password/email', [
    'as'   => 'auth.password',
    'uses' => 'AuthenticationController@getPassword',
]);
Route::post('auth/password/email', [
    'as'   => 'auth.password.post',
    'uses' => 'AuthenticationController@postPassword',
]);
Route::get('auth/password/reset/{email?}/{token?}', [
    'as'   => 'auth.password.reset',
    'uses' => 'AuthenticationController@getReset',
]);
Route::post('auth/password/reset', [
    'as'   => 'auth.password.reset.post',
    'uses' => 'AuthenticationController@postReset',
]);

app/User.php
<?php

namespace App;

use Cartalyst\Sentinel\Users\EloquentUser;

class User extends EloquentUser
{

    /**
     * {@inheritDoc}
     */
    protected $table = 'users';

    /**
     * {@inheritDoc}
     */
    protected $fillable = [
        'email',
        'password',
        'last_name',
        'first_name',
        'permissions',
    ];

    protected $dates = [
        'last_login',
    ];

    public function posts()
    {
        return $this->hasMany('App\Post');
    }
}

resources/views/admin/users/_form.blade.php
<!-- First name form input -->
<div class="form-group">
    {!! Form::label('first_name', 'First name', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::text('first_name', null, ['placeholder' => 'First name', 'class' => 'form-control']) !!}
    </div>
</div>

<!-- Last name form input -->
<div class="form-group">
    {!! Form::label('last_name', 'Last name', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::text('last_name', null, ['placeholder' => 'Last name', 'class' => 'form-control']) !!}
    </div>
</div>

<!-- Email form input -->
<div class="form-group">
    {!! Form::label('email', 'Email', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::text('email', null, ['placeholder' => 'Email', 'class' => 'form-control']) !!}
    </div>
</div>

<!-- Password form input -->
<div class="form-group">
    {!! Form::label('password', 'Password', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::password('password', ['placeholder' => 'Password', 'class' => 'form-control']) !!}
        @if(isset($user->id))
            <p class="help-block">
                Leave empty if you don't want to change this.
            </p>
        @endif
    </div>
</div>

<!-- Role form input -->
<div class="form-group">
    {!! Form::label('role', 'Role', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::select('role[]', $roles, $currentRoles, ['multiple' => 'multiple', 'placeholder' => 'Role', 'class' => 'form-control']) !!}
    </div>
</div>

<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <div class="checkbox">
            <label>
                <input type="checkbox" name="active" value="true" />
                User is activated
            </label>
        </div>
    </div>
</div>

<!-- Save submit button -->
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        {!! Form::submit('Save', ['class' => 'btn btn-primary form-control']) !!}
    </div>
</div>

resources/views/admin/users/create.blade.php
@extends('app')

@section('title')
    New user - Admin panel -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Forums</a></li>
            <li><a href="{{ route('admin.index') }}">Admin panel</a></li>
            <li><a href="{{ route('admin.users.index') }}">Users</a></li>
            <li class="active">New user</li>
        </ol>

        <div class="page-header page-heading">
            <h1>New user</h1>
        </div>

        @include('errors._form')

        {!! Form::model($user = new App\User, ['route' => ['admin.users.store'], 'class' => 'form-horizontal']) !!}
        @include('admin.users._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/users/edit.blade.php
@extends('app')

@section('title')
    Edit user {{ $user->first_name }} {{ $user->last_name }} - Admin panel -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Forums</a></li>
            <li><a href="{{ route('admin.index') }}">Admin panel</a></li>
            <li><a href="{{ route('admin.users.index') }}">Users</a></li>
            <li class="active">Edit user</li>
        </ol>

        <div class="page-header page-heading">
            <h1>Edit user {{ $user->first_name }} {{ $user->last_name }}</h1>
        </div>

        @include('errors._form')

        {!! Form::model($user, ['route' => ['admin.users.update', $user->id], 'method' => 'patch', 'class' => 'form-horizontal']) !!}
        @include('admin.users._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/users/index.blade.php
@extends('app')

@section('title')
    Users - Admin panel -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Forums</a></li>
            <li><a href="{{ route('admin.index') }}">Admin panel</a></li>
            <li class="active">List users</li>
        </ol>

        <div class="page-header page-heading">
            <h1>List users</h1>
        </div>

        <p class="text-right">
            <a class="btn btn-primary btn-lg" href="{{ route('admin.users.create') }}">New User</a>
        </p>

        <table class="table table-striped">
            <thead>
            <tr>
                <th class="text-center">Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Last login</th>
                <th>Created at</th>
                <th class="text-center">Is active</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td class="text-center">{{ $user->id }}</td>
                    <td><a href="{{ route('admin.users.show', [$user->id]) }}">{{ $user->first_name }} {{ $user->last_name }}</a></td>
                    <td>{{ $user->email }}</td>
                    <td>{!! isset($user->last_login) ? '<abbr title="'.$user->last_login->format('d.m.Y H:i:s').'">'.$user->last_login->diffForHumans().'</abbr>' : '<span class="text-muted">never</span>' !!}</td>
                    <td><abbr title="{{ $user->created_at->format('d.m.Y H:i:s') }}">{{ $user->created_at->diffForHumans() }}</abbr></td>
                    <td class="text-center">{!! Activation::completed($user) ? '<i class="fa fa-check text-success"></i>' : '<i class="fa fa-times text-danger"></i>' !!}</td>
                    <td>
                        <a class="btn btn-xs btn-warning" href="{{ route('admin.users.edit', [$user->id]) }}">Edit</a>
                        {!! Form::open(['route' => ['admin.users.destroy', $user->id], 'method' => 'delete', 'style' => 'display:inline']) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop

resources/views/admin/users/show.blade.php
@extends('app')

@section('title')
    User {{ $user->first_name }} {{ $user->last_name }} - Admin panel -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Forums</a></li>
            <li><a href="{{ route('admin.index') }}">Admin panel</a></li>
            <li><a href="{{ route('admin.users.index') }}">Users</a></li>
            <li class="active">Show user</li>
        </ol>

        <div class="page-header page-heading">
            <h1>User {{ $user->first_name }} {{ $user->last_name }}</h1>
        </div>

        <p class="text-right">
            <a class="btn btn-primary btn-lg" href="{{ route('admin.users.edit', [$user->id]) }}">Edit User</a>
        </p>

        <dl class="dl-horizontal">
            <dt>Roles</dt>
            <dd>
                @foreach($user->roles as $i => $role)
                    {{ $role->name }}{{ $i < count($user->roles)-1 ? ', ' : '' }}
                @endforeach
            </dd>

            <dt>Email</dt>
            <dd>{{ $user->email }}</dd>

            <dt>Last login</dt>
            <dd>{!! isset($user->last_login) ? '<abbr title="'.$user->last_login->format('d.m.Y H:i:s').'">'.$user->last_login->diffForHumans().'</abbr>' : '<span class="text-muted">never</span>' !!}</dd>

            <dt>Created at</dt>
            <dd><abbr title="{{ $user->created_at->format('d.m.Y H:i:s') }}">{{ $user->created_at->diffForHumans() }}</abbr></dd>

            <dt>Last update at</dt>
            <dd><abbr title="{{ $user->updated_at->format('d.m.Y H:i:s') }}">{{ $user->updated_at->diffForHumans() }}</abbr></dd>

            <dt>Active</dt>
            <dd>{!! $activation !== false && $activation->completed != false ? '<i class="fa fa-check text-success"></i>' : '<i class="fa fa-times text-danger"></i>' !!}</dd>
        </dl>

        <hr />

        <h2>Lates forum posts</h2>

        <article class="forum-thread">
            @foreach($posts as $i => $post)
                <section class="row row-eq-height">
                    <div class="col-md-3 user-info">
                        <img class="img-thumbnail" src="http://placehold.it/100" alt="{{ $user->first_name }}" /><br />
                        <a href="#">{{ $user->first_name }}</a><br />
                        {{ $user->roles->first()->name }}
                    </div>
                    <div class="col-md-9">
                        <h4 class="pull-left">
                            <a href="{{ route('categories.threads.posts.index', [$post->thread->category->id, $post->thread->id]) }}">{{ $post->title }}</a><br />
                            <small class="text-muted">
                                <abbr title="{{ $post->created_at->format('d.m.Y H:i:s') }}">
                                    <time datetime="{{ $post->created_at->format('d.m.Y H:i:s') }}">{{ $post->created_at->diffForHumans() }}</time>
                                </abbr>
                            </small>
                        </h4>
                        <div class="pull-right" style="padding-top: 10px;">
                            <a href="{{ route('categories.threads.posts.edit', [$post->thread->category->id, $post->thread->id, $post->id]) }}" class="btn btn-primary btn-xs">Edit</a>

                            @if($i == 0)
                                {!! Form::open(['route' => ['categories.threads.destroy', $post->thread->category->id, $post->thread->id], 'method' => 'delete', 'style' => 'display:inline']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                                {!! Form::close() !!}
                            @elseif($i != 0)
                                {!! Form::open(['route' => ['categories.threads.posts.destroy', $post->thread->category->id, $post->thread->id, $post->id], 'method' => 'delete', 'style' => 'display:inline']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                                {!! Form::close() !!}
                            @endif
                        </div>
                        <div class="clearfix"></div>
                        {!! $post->body !!}
                    </div>
                </section>
            @endforeach
        </article>
    </div>
@stop