app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as'   => 'home',
    'uses' => function () {
        return redirect()->route('categories.index');
    }
]);

Route::resource('categories', 'CategoriesController');
Route::resource('categories.threads', 'ThreadsController');
Route::resource('categories.threads.posts', 'PostsController');

Route::group([
    'prefix'     => 'admin',
    'middleware' => 'admin',
], function () {
    Route::get('index', [
        'as'   => 'admin.index',
        'uses' => 'AdminController@index',
    ]);

    Route::resource('categories', 'AdminCategoriesController', [
        'expect' => ['show',],
    ]);

    Route::resource('users', 'AdminUsersController');
});

// Authentication routes
Route::get('auth/login', [
    'as'   => 'auth.login',
    'uses' => 'AuthenticationController@getLogin',
]);
Route::post('auth/login', [
    'as'   => 'auth.login.post',
    'uses' => 'AuthenticationController@postLogin',
]);
Route::get('auth/logout', [
    'as'   => 'auth.logout',
    'uses' => 'AuthenticationController@getLogout',
]);

// Registration routes
Route::get('auth/register', [
    'as'   => 'auth.register',
    'uses' => 'AuthenticationController@getRegister',
]);
Route::post('auth/register', [
    'as'   => 'auth.register.post',
    'uses' => 'AuthenticationController@postRegister',
]);
Route::get('auth/register/confirm/{email?}/{token?}', [
    'as'   => 'auth.register.confirm',
    'uses' => 'AuthenticationController@getConfirm',
]);
Route::post('auth/register/confirm', [
    'as'   => 'auth.register.confirm.post',
    'uses' => 'AuthenticationController@postConfirm',
]);

// Password reset routes
Route::get('auth/password/email', [
    'as'   => 'auth.password',
    'uses' => 'AuthenticationController@getPassword',
]);
Route::post('auth/password/email', [
    'as'   => 'auth.password.post',
    'uses' => 'AuthenticationController@postPassword',
]);
Route::get('auth/password/reset/{email?}/{token?}', [
    'as'   => 'auth.password.reset',
    'uses' => 'AuthenticationController@getReset',
]);
Route::post('auth/password/reset', [
    'as'   => 'auth.password.reset.post',
    'uses' => 'AuthenticationController@postReset',
]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{

    use SoftDeletes;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'description',
        'icon',
    ];

    protected $dates = [
        'deleted_at',
    ];

    public function threads()
    {
        return $this->hasMany('App\Thread');
    }

    public function posts()
    {
        return $this->hasManyThrough('App\Post', 'App\Thread');
    }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests;

class CategoriesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['expect' => ['index']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $categories = Category::with([
            'threads'       => function ($query) {
                $query->orderBy('updated_at', 'desc');
            },
            'threads.posts' => function ($query) {
                $query->orderBy('created_at', 'asc');
            },
            'threads.posts.user',
        ])->get();

        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $categoryId
     * @return Response
     */
    public function show($categoryId)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $categoryId
     * @return Response
     */
    public function edit($categoryId)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $categoryId
     * @return Response
     */
    public function update($categoryId)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $categoryId
     * @return Response
     */
    public function destroy($categoryId)
    {
        //
    }
}

resources/views/admin/categories/_form.blade.php
<!-- Name form input -->
<div class="form-group">
    {!! Form::label('name', 'Name', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::text('name', null, ['placeholder' => 'Name', 'class' => 'form-control', 'required' => 'required']) !!}
    </div>
</div>

<!-- Description form input -->
<div class="form-group">
    {!! Form::label('description', 'Description', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('description', null, ['placeholder' => 'Description', 'class' => 'form-control']) !!}
    </div>
</div>

<!-- Icon form input -->
<div class="form-group">
    {!! Form::label('icon', 'Icon', ['class' => 'control-label col-sm-2']) !!}
    <div class="col-sm-10">
        {!! Form::text('icon', null, ['placeholder' => 'Icon', 'class' => 'form-control']) !!}
    </div>
</div>

<!-- Save submit button -->
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        {!! Form::submit('Save', ['class' => 'btn btn-primary form-control']) !!}
    </div>
</div>

resources/views/admin/categories/create.blade.php
@extends('app')

@section('title')
    New category - Admin panel -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Forums</a></li>
            <li><a href="{{ route('admin.index') }}">Admin panel</a></li>
            <li><a href="{{ route('admin.categories.index') }}">Categories</a></li>
            <li class="active">New category</li>
        </ol>

        <div class="page-header page-heading">
            <h1>New category</h1>
        </div>

        @include('errors._form')

        {!! Form::model($category = new \App\Post, ['route' => ['admin.categories.store'], 'class' => 'form-horizontal']) !!}
        @include('admin.categories._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/categories/edit.blade.php
@extends('app')

@section('title')
    Edit category {{ $category->name }} - Admin panel -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Forums</a></li>
            <li><a href="{{ route('admin.index') }}">Admin panel</a></li>
            <li><a href="{{ route('admin.categories.index') }}">Categories</a></li>
            <li class="active">Edit category</li>
        </ol>

        <div class="page-header page-heading">
            <h1>Edit category {{ $category->name }}</h1>
        </div>

        @include('errors._form')

        {!! Form::model($category, ['route' => ['admin.categories.update', $category->id], 'method' => 'patch', 'class' => 'form-horizontal']) !!}
        @include('admin.categories._form')
        {!! Form::close() !!}
    </div>
@stop

resources/views/admin/categories/index.blade.php
@extends('app')

@section('title')
    Categories - Admin panel -
@stop

@section('content')
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Forums</a></li>
            <li><a href="{{ route('admin.index') }}">Admin panel</a></li>
            <li class="active">List categories</li>
        </ol>

        <div class="page-header page-heading">
            <h1>List categories</h1>
        </div>

        <p class="text-right">
            <a class="btn btn-primary btn-lg" href="{{ route('admin.categories.create') }}">New Category</a>
        </p>

        <table class="table table-striped">
            <thead>
            <tr>
                <th class="text-center">Id</th>
                <th>Name</th>
                <th>Description</th>
                <th class="text-center">Icon</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categories as $category)
                <tr>
                    <td class="text-center">{{ $category->id }}</td>
                    <td>{{ $category->name }}</td>
                    <td>{!! isset($category->description) ? $category->description : '<i>Empty</i>' !!}</td>
                    <td class="text-center">
                        @if(!empty($category->icon))
                            {{ $category->icon }}
                        @else
                            <i class="fa fa-folder fa-2x text-muted"></i>
                        @endif
                    </td>
                    <td>
                        <a class="btn btn-xs btn-warning" href="{{ route('admin.categories.edit', [$category->id]) }}">Edit</a>
                        {!! Form::open(['route' => ['admin.categories.destroy', $category->id], 'method' => 'delete', 'style' => 'display:inline']) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop